#!/bin/bash

cat <<EOF
╔════════════════════════╗
║ web-deploy initializer ║
╚════════════════════════╝

this is for 'systemd' machines.
this will fail if there is no 'systemctl'.

we'll use 'sudo' to move files to their appropriate places in the file system.
inspect this file before executing if this is of concern to you.
otherwise, we'll write the 'sudo' commands to the console before executing.

EOF

# check if systemctl exists on the system
command -v systemctl > /dev/null

# if `systemctl` isn't found, say that, then exit w code 1
[ $? -ne 0 ] && \
    echo "[error]: you'll need systemd for this, but 'systemctl' is not found" && \
    exit 1

# exit if anything fails
set -e

echo "'sudo cp web-deploy /usr/local/bin/web-deploy'"
echo "this command moves the 'web-deploy' script into the local executables directory"
sudo cp web-deploy /usr/local/bin/web-deploy

echo "sudo cp web-deploy.service /etc/systemd/system/web-deploy.service"
echo "this command moves the 'web-deploy.service' unit to the systemd service directory"
sudo cp web-deploy.service /etc/systemd/system/web-deploy.service

echo "sudo cp web-deploy.timer /etc/systemd/system/web-deploy.timer"
echo "this command moves the 'web-deploy.timer' unit to the systemd service directory"
sudo cp web-deploy.timer /etc/systemd/system/web-deploy.timer
